# Generated by Django 4.2.9 on 2024-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
