# Generated by Django 4.2.9 on 2024-03-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_status'),
        ('app', '0003_item'),
    ]

    operations = [
    ]
