# Generated by Django 4.2.11 on 2024-03-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advancement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='advancement',
            field=models.IntegerField(default=0),
        ),
    ]
