# Generated by Django 4.2.11 on 2024-03-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_advancement_alter_task_advancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='est_days',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
