# Generated by Django 4.2.11 on 2024-03-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_est_days_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubtask',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='tasksubtask',
            name='task',
        ),
        migrations.DeleteModel(
            name='RequiredTask',
        ),
        migrations.DeleteModel(
            name='TaskSubtask',
        ),
    ]
