# Generated by Django 4.2.11 on 2024-03-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tasksubtask_subtask_remove_tasksubtask_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_tasks',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='app.task', verbose_name='Required tasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='parent_tasks', to='app.task', verbose_name='Subtasks'),
        ),
    ]
