# Generated by Django 4.2.10 on 2024-03-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_task_description_alter_task_est_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asigned_users',
            field=models.ManyToManyField(blank=True, related_name='asigned_tasks', to='app.user', verbose_name='Asigned users'),
        ),
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_tasks', to='app.user'),
            preserve_default=False,
        ),
    ]
