# Generated by Django 4.2.10 on 2024-03-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_task_description_alter_task_est_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
