# Generated by Django 4.2.10 on 2024-03-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_item_task_asigned_users_task_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_users',
            new_name='assigned_users',
        ),
    ]
