# Generated by Django 4.2.9 on 2024-03-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_conges'),
        ('app', '0009_delete_item_task_asigned_users_task_manager'),
        ('app', '0010_rename_asigned_users_task_assigned_users'),
    ]

    operations = [
    ]
