# Generated by Django 4.2.9 on 2024-03-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_conges_malade_alter_conges_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conges',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conges', to='app.user'),
        ),
    ]
